version: '3'
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blog
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=R1bka171
      - POSTGRES_DB=blog
    ports:
      - 5000:5432
    restart: always
  flyway:
    image: flyway/flyway
#    command: -url=jdbc:postgresql://db:5432/blog  -schemas=public -user=postgres -password=somepassword migrate
    volumes:
      - ./src/main/resources/db/migration/:/flyway/sql/
    restart: on-failure
    depends_on:
      - db